"""Add_Modules

Revision ID: 41745a2b1bf7
Revises: 014_governance_schema
Create Date: 2026-04-13 21:36:09.430453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import edulafia

# revision identifiers, used by Alembic.
revision: str = '41745a2b1bf7'
down_revision: Union[str, None] = '014_governance_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accreditation_checklists_inspected_by_fkey', 'accreditation_checklists', type_='foreignkey')
    op.drop_constraint('assets_assigned_to_fkey', 'assets', type_='foreignkey')
    op.drop_constraint(op.f('book_lendings_student_id_fkey'), 'book_lendings', type_='foreignkey')
    op.drop_constraint(op.f('bus_attendance_route_id_fkey'), 'bus_attendance', type_='foreignkey')
    op.drop_constraint(op.f('campaigns_created_by_fkey'), 'campaigns', type_='foreignkey')
    op.drop_constraint(op.f('uq_club_membership'), 'club_memberships', type_='unique')
    op.drop_constraint(op.f('custody_orders_school_id_fkey'), 'custody_orders', type_='foreignkey')
    op.drop_constraint(op.f('custody_orders_created_by_fkey'), 'custody_orders', type_='foreignkey')
    op.drop_constraint(op.f('custody_orders_custodial_parent_id_fkey'), 'custody_orders', type_='foreignkey')
    op.drop_constraint(op.f('custody_orders_non_custodial_parent_id_fkey'), 'custody_orders', type_='foreignkey')
    op.drop_constraint(op.f('data_archives_created_by_fkey'), 'data_archives', type_='foreignkey')
    op.drop_constraint('discipline_records_reported_by_fkey', 'discipline_records', type_='foreignkey')
    op.drop_constraint(op.f('exam_registrations_student_id_fkey'), 'exam_registrations', type_='foreignkey')
    op.drop_constraint(op.f('girl_child_records_created_by_fkey'), 'girl_child_records', type_='foreignkey')
    op.drop_constraint(op.f('meal_records_meal_plan_id_fkey'), 'meal_records', type_='foreignkey')
    op.drop_constraint(op.f('ministry_reports_generated_by_fkey'), 'ministry_reports', type_='foreignkey')
    op.drop_constraint(op.f('payroll_runs_created_by_fkey'), 'payroll_runs', type_='foreignkey')
    op.drop_constraint(op.f('school_inspections_created_by_fkey'), 'school_inspections', type_='foreignkey')
    op.drop_constraint(op.f('smc_reports_created_by_fkey'), 'smc_reports', type_='foreignkey')
    op.drop_constraint(op.f('waec_bulk_registrations_created_by_fkey'), 'waec_bulk_registrations', type_='foreignkey')
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_class_id'), 'assignments', ['class_id'], unique=False)
    op.create_index(op.f('ix_assignments_subject_id'), 'assignments', ['subject_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_projects_school_id'), 'building_projects', ['school_id'], unique=False)
    op.create_index(op.f('ix_building_projects_status'), 'building_projects', ['status'], unique=False)
    op.create_table('hostels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False, comment='male, female, mixed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_school_id'), 'hostels', ['school_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False, comment='access, correction, erasure, portability'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, in_progress, completed, rejected'),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_requester_id'), 'data_subject_requests', ['requester_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_school_id'), 'events', ['school_id'], unique=False)
    op.create_table('messages',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostel_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_hostel_id'), 'rooms', ['hostel_id'], unique=False)
    op.create_table('alumni_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('current_occupation', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_profiles_school_id'), 'alumni_profiles', ['school_id'], unique=False)
    op.create_index(op.f('ix_alumni_profiles_student_id'), 'alumni_profiles', ['student_id'], unique=True)
    op.create_table('bed_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_allocations_academic_year_id'), 'bed_allocations', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_bed_allocations_room_id'), 'bed_allocations', ['room_id'], unique=False)
    op.create_index(op.f('ix_bed_allocations_student_id'), 'bed_allocations', ['student_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False, comment='medical_processing, general_data, photo_release'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='granted, revoked'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_student_id'), 'consent_records', ['student_id'], unique=False)
    op.drop_index(op.f('ix_projects_school_id'), table_name='projects')
    op.drop_table('projects')
    op.alter_column('absence_excusals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, approved, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('academic_results', 'flag',
               existing_type=sa.VARCHAR(length=10),
               comment='Special flags: ABS (absent), INC (incomplete), CHEAT (cheating)',
               existing_nullable=True)
    op.drop_index(op.f('idx_academic_results_class_term'), table_name='academic_results')
    op.drop_index(op.f('idx_academic_results_school_term'), table_name='academic_results')
    op.drop_index(op.f('idx_academic_results_student_term'), table_name='academic_results')
    op.drop_index(op.f('idx_academic_results_subject_term'), table_name='academic_results')
    op.add_column('academic_years', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('academic_years', 'is_current')
    op.alter_column('accreditation_checklists', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('accreditation_checklists', 'requirement',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('accreditation_checklists', 'inspected_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('accreditation_checklists', 'inspected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('applications', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'exam_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('applications', 'interview_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.alter_column('assets', 'unit_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('assets', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('assets', 'depreciation_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.drop_index(op.f('idx_attendance_notification_status'), table_name='attendance_notifications')
    op.drop_index(op.f('idx_attendance_pattern_type'), table_name='attendance_patterns')
    op.drop_index(op.f('idx_attendance_record_date'), table_name='attendance_records')
    op.add_column('book_lendings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('book_lendings', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_book_lendings_status'), 'book_lendings', ['status'], unique=False)
    op.create_index(op.f('ix_book_lendings_student_id'), 'book_lendings', ['student_id'], unique=False)
    op.create_foreign_key(None, 'book_lendings', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('bus_attendance', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_bus_attendance_route_id'), 'bus_attendance', ['route_id'], unique=False)
    op.create_foreign_key(None, 'bus_attendance', 'bus_routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bus_routes', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('bus_routes', 'driver_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bus_routes', 'driver_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('bus_stops', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bus_stops', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bus_stops', 'location',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('bus_stops', 'stop_order')
    op.alter_column('campaigns', 'target_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('campaigns', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.drop_column('campaigns', 'created_by')
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('classes', 'level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_column('classes', 'academic_year')
    op.drop_column('classes', 'section')
    op.add_column('club_memberships', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('clubs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('clubs', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('communication_recipients', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='sent, delivered, read, acknowledged',
               existing_nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
    op.add_column('custody_orders', sa.Column('custodial_guardian_id', sa.UUID(), nullable=False))
    op.add_column('custody_orders', sa.Column('non_custodial_guardian_id', sa.UUID(), nullable=True))
    op.alter_column('custody_orders', 'court_order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('custody_orders', 'court_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('custody_orders', 'restrictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_custody_orders_school_id'), table_name='custody_orders')
    op.create_index(op.f('ix_custody_orders_custodial_guardian_id'), 'custody_orders', ['custodial_guardian_id'], unique=False)
    op.create_foreign_key(None, 'custody_orders', 'student_guardians', ['custodial_guardian_id'], ['id'])
    op.create_foreign_key(None, 'custody_orders', 'student_guardians', ['non_custodial_guardian_id'], ['id'])
    op.drop_column('custody_orders', 'custodial_parent_id')
    op.drop_column('custody_orders', 'school_id')
    op.drop_column('custody_orders', 'non_custodial_parent_id')
    op.drop_column('custody_orders', 'created_by')
    op.add_column('data_archives', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('data_archives', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('data_archives', 'data_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('data_archives', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_index(op.f('ix_data_archives_status'), 'data_archives', ['status'], unique=False)
    op.drop_column('data_archives', 'created_by')
    op.alter_column('discipline_records', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('discipline_records', 'action_taken',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('discipline_records', 'reported_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_discipline_records_status'), 'discipline_records', ['status'], unique=False)
    op.add_column('donations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('donations', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('emergency_modes', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='pandemic, security, natural_disaster, other',
               existing_nullable=False)
    op.alter_column('emergency_modes', 'protocols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Specific protocols enabled during emergency',
               existing_nullable=True)
    op.alter_column('exam_registrations', 'subjects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_exam_registrations_status'), 'exam_registrations', ['status'], unique=False)
    op.create_foreign_key(None, 'exam_registrations', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fee_ledger', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment='cash, bank_transfer, paystack, flutterwave, remita, cheque',
               existing_nullable=True)
    op.drop_index(op.f('idx_fee_ledger_school_date'), table_name='fee_ledger')
    op.drop_index(op.f('idx_fee_ledger_student_date'), table_name='fee_ledger')
    op.drop_index(op.f('idx_fee_ledger_type_date'), table_name='fee_ledger')
    op.alter_column('generated_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, generating, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('girl_child_records', 'enrollment_source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('girl_child_records', 'risk_factors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('girl_child_records', 'interventions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.execute("ALTER TABLE girl_child_records ALTER COLUMN attendance_trend TYPE FLOAT USING attendance_trend::double precision")
    op.create_index(op.f('ix_girl_child_records_dropout_risk'), 'girl_child_records', ['dropout_risk'], unique=False)
    op.create_unique_constraint('uq_girl_child_student', 'girl_child_records', ['student_id'])
    op.drop_column('girl_child_records', 'created_by')
    op.drop_index(op.f('idx_guardian_school'), table_name='guardians')
    op.alter_column('health_screenings', 'screening_type',
               existing_type=sa.VARCHAR(length=50),
               comment='annual, pre_sports, special',
               existing_nullable=False)
    op.alter_column('health_screenings', 'dental_notes',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.alter_column('health_screenings', 'follow_up_notes',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_health_screenings_school_date'), table_name='health_screenings')
    op.drop_index(op.f('idx_health_screenings_student_date'), table_name='health_screenings')
    op.alter_column('individual_education_plans', 'disability_type',
               existing_type=sa.VARCHAR(length=50),
               comment='visual, hearing, mobility, cognitive, autism, other',
               existing_nullable=False)
    op.alter_column('individual_education_plans', 'goals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of goal objects',
               existing_nullable=True)
    op.alter_column('leave_requests', 'leave_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.alter_column('meal_plans', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_meal_records_meal_plan_id'), 'meal_records', ['meal_plan_id'], unique=False)
    op.create_foreign_key(None, 'meal_records', 'meal_plans', ['meal_plan_id'], ['id'], ondelete='CASCADE')
    op.add_column('ministry_reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('ministry_reports', 'period_start',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ministry_reports', 'period_end',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ministry_reports', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ministry_reports', 'generated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('otp_verifications', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               comment='login, password_reset, transaction',
               existing_nullable=False)
    op.alter_column('parent_correction_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, approved, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('parent_feedback', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, reviewed, responded',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('parent_notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment='whatsapp, sms, in_app',
               existing_nullable=False)
    op.alter_column('parent_notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='low, normal, high, urgent',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('parent_notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, sent, delivered, read, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('payment_configurations', 'payment_gateway',
               existing_type=sa.VARCHAR(length=50),
               comment='paystack, flutterwave, remita',
               existing_nullable=False)
    op.alter_column('payment_configurations', 'secret_key',
               existing_type=sa.VARCHAR(length=255),
               comment='Encrypted',
               existing_nullable=True)
    op.alter_column('payment_configurations', 'webhook_secret',
               existing_type=sa.VARCHAR(length=255),
               comment='Encrypted',
               existing_nullable=True)
    op.add_column('payroll_entries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('payroll_entries', 'gross_pay',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'pension',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'nhf',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'other_deductions',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'net_pay',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_payroll_entries_staff_id'), 'payroll_entries', ['staff_id'], unique=False)
    op.alter_column('payroll_runs', 'total_gross',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_runs', 'total_deductions',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_runs', 'total_net',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payroll_runs', 'run_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_payroll_runs_status'), 'payroll_runs', ['status'], unique=False)
    op.drop_column('payroll_runs', 'created_by')
    op.alter_column('referrals', 'reason',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=False)
    op.alter_column('referrals', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='urgent, normal, follow_up',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('referrals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, sent, acknowledged, attended, completed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('referrals', 'outcome_notes',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_referrals_school_date'), table_name='referrals')
    op.drop_index(op.f('idx_referrals_student_date'), table_name='referrals')
    op.drop_index(op.f('idx_report_cards_class_term'), table_name='report_cards')
    op.drop_index(op.f('idx_report_cards_student_term'), table_name='report_cards')
    op.alter_column('research_data_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, approved, rejected, fulfilled',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('retention_policies', 'data_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('school_inspections', 'findings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('school_inspections', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('school_inspections', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.create_index(op.f('ix_school_inspections_status'), 'school_inspections', ['status'], unique=False)
    op.drop_column('school_inspections', 'created_by')
    op.alter_column('school_kpi_snapshots', 'trend',
               existing_type=sa.VARCHAR(length=10),
               comment='up, down, stable',
               existing_nullable=True)
    op.alter_column('school_kpi_snapshots', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='critical, warning, normal',
               existing_nullable=False)
    op.alter_column('school_training_assignments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='assigned, in_progress, completed, overdue',
               existing_nullable=False,
               existing_server_default=sa.text("'assigned'::character varying"))
    op.alter_column('sentinel_signals', 'threshold_type',
               existing_type=sa.VARCHAR(length=50),
               comment='class_cluster, school_cluster, lga_cluster',
               existing_nullable=False)
    op.alter_column('sentinel_signals', 'alert_tier',
               existing_type=sa.VARCHAR(length=20),
               comment='school, lga, state',
               existing_nullable=False)
    op.alter_column('sentinel_signals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active, acknowledged, resolved, false_positive',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_sentinel_signals_state_date'), table_name='sentinel_signals')
    op.alter_column('sick_bay_visits', 'presenting_complaint_notes',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.alter_column('sick_bay_visits', 'treatment_given',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.alter_column('sick_bay_visits', 'outcome',
               existing_type=sa.VARCHAR(length=50),
               comment='returned_to_class, sent_home, referred, hospitalized',
               existing_nullable=False)
    op.drop_index(op.f('idx_sick_bay_visits_school_date'), table_name='sick_bay_visits')
    op.drop_index(op.f('idx_sick_bay_visits_student_date'), table_name='sick_bay_visits')
    op.add_column('smc_reports', sa.Column('meeting_minutes', sa.Text(), nullable=True))
    op.alter_column('smc_reports', 'report_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('smc_reports', 'attendance_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('smc_reports', 'financial_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('smc_reports', 'action_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('smc_reports', 'meeting_notes')
    op.drop_column('smc_reports', 'created_by')
    op.alter_column('staff', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='teacher, nurse, bursar, admin, accountant, librarian, lab_attendant, security, cleaner, other',
               existing_comment='teacher, nurse, bursar, admin',
               existing_nullable=False)
    op.alter_column('staff', 'employment_type',
               existing_type=sa.VARCHAR(length=20),
               comment='permanent, contract, nysc, intern',
               existing_nullable=False,
               existing_server_default=sa.text("'permanent'::character varying"))
    op.alter_column('staff', 'bank_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=edulafia.core.encryption.EncryptedJSON(),
               comment='Encrypted',
               existing_nullable=True)
    op.alter_column('staff', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active, inactive, on_leave, terminated, retired',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_staff_employment_type'), table_name='staff')
    op.drop_index(op.f('idx_staff_role'), table_name='staff')
    op.drop_index(op.f('idx_staff_status'), table_name='staff')
    op.alter_column('staff_class_assignments', 'assignment_type',
               existing_type=sa.VARCHAR(length=20),
               comment='regular, substitute, temporary',
               existing_nullable=False,
               existing_server_default=sa.text("'regular'::character varying"))
    op.alter_column('staff_communications', 'communication_type',
               existing_type=sa.VARCHAR(length=50),
               comment='announcement, broadcast, message, meeting',
               existing_nullable=False)
    op.alter_column('staff_communications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='low, normal, high, urgent',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.drop_index(op.f('idx_student_guardian_guardian'), table_name='student_guardians')
    op.drop_index(op.f('idx_student_guardian_student'), table_name='student_guardians')
    op.alter_column('student_health_profiles', 'emergency_notes',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.alter_column('student_health_profiles', 'family_health_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=edulafia.core.encryption.EncryptedJSON(),
               existing_nullable=True)
    op.alter_column('students', 'chronic_conditions',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.alter_column('students', 'allergies',
               existing_type=sa.TEXT(),
               type_=edulafia.core.encryption.EncryptedString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_student_class'), table_name='students')
    op.drop_index(op.f('idx_student_school_status'), table_name='students')
    op.alter_column('sync_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='started, completed, failed, partial',
               existing_nullable=False)
    op.alter_column('sync_status', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment='synced, pending, failed, conflict',
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('system_updates', 'release_type',
               existing_type=sa.VARCHAR(length=20),
               comment='major, minor, patch, hotfix',
               existing_nullable=False)
    op.alter_column('system_updates', 'deployment_type',
               existing_type=sa.VARCHAR(length=20),
               comment='global, school_specific, regional',
               existing_nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('system_updates', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, staging, deploying, deployed, rolled_back',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('teacher_attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='present, absent, late, excused, on_leave',
               existing_nullable=False)
    op.alter_column('teacher_attendance', 'check_in_method',
               existing_type=sa.VARCHAR(length=20),
               comment='manual, qr_code, geofencing',
               existing_nullable=True)
    op.add_column('terms', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('terms', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_terms_academic_year_id'), 'terms', ['academic_year_id'], unique=False)
    op.create_foreign_key(None, 'terms', 'academic_years', ['academic_year_id'], ['id'], ondelete='CASCADE')
    op.drop_column('terms', 'is_current')
    op.alter_column('training_resources', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment='video, guide, document, interactive',
               existing_nullable=False)
    op.alter_column('training_resources', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='onboarding, module_specific, advanced, troubleshooting',
               existing_nullable=False)
    op.alter_column('training_resources', 'language',
               existing_type=sa.VARCHAR(length=20),
               comment='en, ig, ha',
               existing_nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_index(op.f('idx_vaccination_records_student_date'), table_name='vaccination_records')
    op.alter_column('waec_bulk_registrations', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('waec_bulk_registrations', 'students',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('waec_bulk_registrations', 'total_paid',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.create_index(op.f('ix_waec_bulk_registrations_class_id'), 'waec_bulk_registrations', ['class_id'], unique=False)
    op.create_index(op.f('ix_waec_bulk_registrations_status'), 'waec_bulk_registrations', ['status'], unique=False)
    op.drop_column('waec_bulk_registrations', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waec_bulk_registrations', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('waec_bulk_registrations_created_by_fkey'), 'waec_bulk_registrations', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_waec_bulk_registrations_status'), table_name='waec_bulk_registrations')
    op.drop_index(op.f('ix_waec_bulk_registrations_class_id'), table_name='waec_bulk_registrations')
    op.alter_column('waec_bulk_registrations', 'total_paid',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('waec_bulk_registrations', 'students',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('waec_bulk_registrations', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_vaccination_records_student_date'), 'vaccination_records', ['student_id', 'administration_date'], unique=False)
    op.alter_column('training_resources', 'language',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='en, ig, ha',
               existing_nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('training_resources', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='onboarding, module_specific, advanced, troubleshooting',
               existing_nullable=False)
    op.alter_column('training_resources', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='video, guide, document, interactive',
               existing_nullable=False)
    op.add_column('terms', sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'terms', type_='foreignkey')
    op.drop_index(op.f('ix_terms_academic_year_id'), table_name='terms')
    op.alter_column('terms', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('terms', 'is_active')
    op.alter_column('teacher_attendance', 'check_in_method',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='manual, qr_code, geofencing',
               existing_nullable=True)
    op.alter_column('teacher_attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='present, absent, late, excused, on_leave',
               existing_nullable=False)
    op.alter_column('system_updates', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, staging, deploying, deployed, rolled_back',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('system_updates', 'deployment_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='global, school_specific, regional',
               existing_nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('system_updates', 'release_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='major, minor, patch, hotfix',
               existing_nullable=False)
    op.alter_column('sync_status', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='synced, pending, failed, conflict',
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('sync_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='started, completed, failed, partial',
               existing_nullable=False)
    op.create_index(op.f('idx_student_school_status'), 'students', ['school_id', 'status'], unique=False)
    op.create_index(op.f('idx_student_class'), 'students', ['class_id', 'status'], unique=False)
    op.alter_column('students', 'allergies',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('students', 'chronic_conditions',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student_health_profiles', 'family_health_history',
               existing_type=edulafia.core.encryption.EncryptedJSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('student_health_profiles', 'emergency_notes',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_student_guardian_student'), 'student_guardians', ['student_id'], unique=False)
    op.create_index(op.f('idx_student_guardian_guardian'), 'student_guardians', ['guardian_id'], unique=False)
    op.alter_column('staff_communications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='low, normal, high, urgent',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('staff_communications', 'communication_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='announcement, broadcast, message, meeting',
               existing_nullable=False)
    op.alter_column('staff_class_assignments', 'assignment_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='regular, substitute, temporary',
               existing_nullable=False,
               existing_server_default=sa.text("'regular'::character varying"))
    op.create_index(op.f('idx_staff_status'), 'staff', ['school_id', 'status'], unique=False)
    op.create_index(op.f('idx_staff_role'), 'staff', ['school_id', 'role'], unique=False)
    op.create_index(op.f('idx_staff_employment_type'), 'staff', ['school_id', 'employment_type'], unique=False)
    op.alter_column('staff', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active, inactive, on_leave, terminated, retired',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('staff', 'bank_details',
               existing_type=edulafia.core.encryption.EncryptedJSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Encrypted',
               existing_nullable=True)
    op.alter_column('staff', 'employment_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='permanent, contract, nysc, intern',
               existing_nullable=False,
               existing_server_default=sa.text("'permanent'::character varying"))
    op.alter_column('staff', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='teacher, nurse, bursar, admin',
               existing_comment='teacher, nurse, bursar, admin, accountant, librarian, lab_attendant, security, cleaner, other',
               existing_nullable=False)
    op.add_column('smc_reports', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('smc_reports', sa.Column('meeting_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('smc_reports_created_by_fkey'), 'smc_reports', 'users', ['created_by'], ['id'])
    op.alter_column('smc_reports', 'action_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('smc_reports', 'financial_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('smc_reports', 'attendance_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('smc_reports', 'report_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('smc_reports', 'meeting_minutes')
    op.create_index(op.f('idx_sick_bay_visits_student_date'), 'sick_bay_visits', ['student_id', 'visit_date'], unique=False)
    op.create_index(op.f('idx_sick_bay_visits_school_date'), 'sick_bay_visits', ['school_id', 'visit_date'], unique=False)
    op.alter_column('sick_bay_visits', 'outcome',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='returned_to_class, sent_home, referred, hospitalized',
               existing_nullable=False)
    op.alter_column('sick_bay_visits', 'treatment_given',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sick_bay_visits', 'presenting_complaint_notes',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_sentinel_signals_state_date'), 'sentinel_signals', ['state', 'date_generated'], unique=False)
    op.alter_column('sentinel_signals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active, acknowledged, resolved, false_positive',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('sentinel_signals', 'alert_tier',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='school, lga, state',
               existing_nullable=False)
    op.alter_column('sentinel_signals', 'threshold_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='class_cluster, school_cluster, lga_cluster',
               existing_nullable=False)
    op.alter_column('school_training_assignments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='assigned, in_progress, completed, overdue',
               existing_nullable=False,
               existing_server_default=sa.text("'assigned'::character varying"))
    op.alter_column('school_kpi_snapshots', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='critical, warning, normal',
               existing_nullable=False)
    op.alter_column('school_kpi_snapshots', 'trend',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='up, down, stable',
               existing_nullable=True)
    op.add_column('school_inspections', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('school_inspections_created_by_fkey'), 'school_inspections', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_school_inspections_status'), table_name='school_inspections')
    op.alter_column('school_inspections', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('school_inspections', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('school_inspections', 'findings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('retention_policies', 'data_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('research_data_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, approved, rejected, fulfilled',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('idx_report_cards_student_term'), 'report_cards', ['student_id', 'term_id'], unique=False)
    op.create_index(op.f('idx_report_cards_class_term'), 'report_cards', ['class_id', 'term_id'], unique=False)
    op.create_index(op.f('idx_referrals_student_date'), 'referrals', ['student_id', 'referral_date'], unique=False)
    op.create_index(op.f('idx_referrals_school_date'), 'referrals', ['school_id', 'referral_date'], unique=False)
    op.alter_column('referrals', 'outcome_notes',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('referrals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, sent, acknowledged, attended, completed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('referrals', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='urgent, normal, follow_up',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('referrals', 'reason',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('payroll_runs', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payroll_runs_created_by_fkey'), 'payroll_runs', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_payroll_runs_status'), table_name='payroll_runs')
    op.alter_column('payroll_runs', 'run_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('payroll_runs', 'total_net',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_runs', 'total_deductions',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_runs', 'total_gross',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_payroll_entries_staff_id'), table_name='payroll_entries')
    op.alter_column('payroll_entries', 'net_pay',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'other_deductions',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'nhf',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'pension',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'tax',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'gross_pay',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('payroll_entries', 'updated_at')
    op.alter_column('payment_configurations', 'webhook_secret',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Encrypted',
               existing_nullable=True)
    op.alter_column('payment_configurations', 'secret_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Encrypted',
               existing_nullable=True)
    op.alter_column('payment_configurations', 'payment_gateway',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='paystack, flutterwave, remita',
               existing_nullable=False)
    op.alter_column('parent_notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, sent, delivered, read, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('parent_notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='low, normal, high, urgent',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('parent_notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='whatsapp, sms, in_app',
               existing_nullable=False)
    op.alter_column('parent_feedback', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, reviewed, responded',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('parent_correction_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, approved, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('otp_verifications', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='login, password_reset, transaction',
               existing_nullable=False)
    op.create_foreign_key(op.f('ministry_reports_generated_by_fkey'), 'ministry_reports', 'users', ['generated_by'], ['id'])
    op.alter_column('ministry_reports', 'generated_by',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('ministry_reports', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('ministry_reports', 'period_end',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('ministry_reports', 'period_start',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('ministry_reports', 'updated_at')
    op.drop_constraint(None, 'meal_records', type_='foreignkey')
    op.create_foreign_key(op.f('meal_records_meal_plan_id_fkey'), 'meal_records', 'meal_plans', ['meal_plan_id'], ['id'])
    op.drop_index(op.f('ix_meal_records_meal_plan_id'), table_name='meal_records')
    op.alter_column('meal_plans', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('leave_requests', 'leave_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('individual_education_plans', 'goals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Array of goal objects',
               existing_nullable=True)
    op.alter_column('individual_education_plans', 'disability_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='visual, hearing, mobility, cognitive, autism, other',
               existing_nullable=False)
    op.create_index(op.f('idx_health_screenings_student_date'), 'health_screenings', ['student_id', 'screening_date'], unique=False)
    op.create_index(op.f('idx_health_screenings_school_date'), 'health_screenings', ['school_id', 'screening_date'], unique=False)
    op.alter_column('health_screenings', 'follow_up_notes',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('health_screenings', 'dental_notes',
               existing_type=edulafia.core.encryption.EncryptedString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('health_screenings', 'screening_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='annual, pre_sports, special',
               existing_nullable=False)
    op.create_index(op.f('idx_guardian_school'), 'guardians', ['school_id'], unique=False)
    op.add_column('girl_child_records', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('girl_child_records_created_by_fkey'), 'girl_child_records', 'users', ['created_by'], ['id'])
    op.drop_constraint('uq_girl_child_student', 'girl_child_records', type_='unique')
    op.drop_index(op.f('ix_girl_child_records_dropout_risk'), table_name='girl_child_records')
    op.alter_column('girl_child_records', 'attendance_trend',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('girl_child_records', 'interventions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('girl_child_records', 'risk_factors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('girl_child_records', 'enrollment_source',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('generated_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, generating, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('idx_fee_ledger_type_date'), 'fee_ledger', ['transaction_type', 'transaction_date'], unique=False)
    op.create_index(op.f('idx_fee_ledger_student_date'), 'fee_ledger', ['student_id', 'transaction_date'], unique=False)
    op.create_index(op.f('idx_fee_ledger_school_date'), 'fee_ledger', ['school_id', 'transaction_date'], unique=False)
    op.alter_column('fee_ledger', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='cash, bank_transfer, paystack, flutterwave, remita, cheque',
               existing_nullable=True)
    op.drop_constraint(None, 'exam_registrations', type_='foreignkey')
    op.create_foreign_key(op.f('exam_registrations_student_id_fkey'), 'exam_registrations', 'students', ['student_id'], ['id'])
    op.drop_index(op.f('ix_exam_registrations_status'), table_name='exam_registrations')
    op.alter_column('exam_registrations', 'subjects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('emergency_modes', 'protocols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Specific protocols enabled during emergency',
               existing_nullable=True)
    op.alter_column('emergency_modes', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pandemic, security, natural_disaster, other',
               existing_nullable=False)
    op.alter_column('donations', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('donations', 'updated_at')
    op.create_foreign_key(op.f('discipline_records_reported_by_fkey'), 'discipline_records', 'users', ['reported_by'], ['id'])
    op.drop_index(op.f('ix_discipline_records_status'), table_name='discipline_records')
    op.alter_column('discipline_records', 'reported_by',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('discipline_records', 'action_taken',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('discipline_records', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('data_archives', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('data_archives_created_by_fkey'), 'data_archives', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_data_archives_status'), table_name='data_archives')
    op.alter_column('data_archives', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('data_archives', 'data_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('data_archives', 'updated_at')
    op.drop_column('data_archives', 'created_at')
    op.add_column('custody_orders', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('custody_orders', sa.Column('non_custodial_parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('custody_orders', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('custody_orders', sa.Column('custodial_parent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'custody_orders', type_='foreignkey')
    op.drop_constraint(None, 'custody_orders', type_='foreignkey')
    op.create_foreign_key(op.f('custody_orders_non_custodial_parent_id_fkey'), 'custody_orders', 'guardians', ['non_custodial_parent_id'], ['id'])
    op.create_foreign_key(op.f('custody_orders_custodial_parent_id_fkey'), 'custody_orders', 'guardians', ['custodial_parent_id'], ['id'])
    op.create_foreign_key(op.f('custody_orders_created_by_fkey'), 'custody_orders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('custody_orders_school_id_fkey'), 'custody_orders', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_custody_orders_custodial_guardian_id'), table_name='custody_orders')
    op.create_index(op.f('ix_custody_orders_school_id'), 'custody_orders', ['school_id'], unique=False)
    op.alter_column('custody_orders', 'restrictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('custody_orders', 'court_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('custody_orders', 'court_order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('custody_orders', 'non_custodial_guardian_id')
    op.drop_column('custody_orders', 'custodial_guardian_id')
    op.alter_column('communication_recipients', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='sent, delivered, read, acknowledged',
               existing_nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('clubs', 'category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('clubs', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_club_membership'), 'club_memberships', ['club_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('club_memberships', 'updated_at')
    op.add_column('classes', sa.Column('section', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('classes', 'level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('classes', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('campaigns', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('campaigns_created_by_fkey'), 'campaigns', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.alter_column('campaigns', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('campaigns', 'target_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.add_column('bus_stops', sa.Column('stop_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('bus_stops', 'location',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('bus_stops', 'updated_at')
    op.drop_column('bus_stops', 'created_at')
    op.alter_column('bus_routes', 'driver_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bus_routes', 'driver_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bus_routes', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'bus_attendance', type_='foreignkey')
    op.create_foreign_key(op.f('bus_attendance_route_id_fkey'), 'bus_attendance', 'bus_routes', ['route_id'], ['id'])
    op.drop_index(op.f('ix_bus_attendance_route_id'), table_name='bus_attendance')
    op.drop_column('bus_attendance', 'updated_at')
    op.alter_column('books', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'book_lendings', type_='foreignkey')
    op.create_foreign_key(op.f('book_lendings_student_id_fkey'), 'book_lendings', 'students', ['student_id'], ['id'])
    op.drop_index(op.f('ix_book_lendings_student_id'), table_name='book_lendings')
    op.drop_index(op.f('ix_book_lendings_status'), table_name='book_lendings')
    op.alter_column('book_lendings', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('book_lendings', 'updated_at')
    op.create_index(op.f('idx_attendance_record_date'), 'attendance_records', ['school_id', 'date'], unique=False)
    op.create_index(op.f('idx_attendance_pattern_type'), 'attendance_patterns', ['school_id', 'pattern_type'], unique=False)
    op.create_index(op.f('idx_attendance_notification_status'), 'attendance_notifications', ['status'], unique=False)
    op.create_foreign_key(op.f('assets_assigned_to_fkey'), 'assets', 'users', ['assigned_to'], ['id'])
    op.alter_column('assets', 'depreciation_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('assets', 'assigned_to',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('assets', 'unit_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.alter_column('applications', 'interview_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('applications', 'exam_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('applications', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(op.f('accreditation_checklists_inspected_by_fkey'), 'accreditation_checklists', 'users', ['inspected_by'], ['id'])
    op.alter_column('accreditation_checklists', 'inspected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('accreditation_checklists', 'inspected_by',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('accreditation_checklists', 'requirement',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('accreditation_checklists', 'category',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('academic_years', sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('academic_years', 'is_active')
    op.create_index(op.f('idx_academic_results_subject_term'), 'academic_results', ['subject_id', 'term_id'], unique=False)
    op.create_index(op.f('idx_academic_results_student_term'), 'academic_results', ['student_id', 'term_id'], unique=False)
    op.create_index(op.f('idx_academic_results_school_term'), 'academic_results', ['school_id', 'term_id'], unique=False)
    op.create_index(op.f('idx_academic_results_class_term'), 'academic_results', ['class_id', 'term_id'], unique=False)
    op.alter_column('academic_results', 'flag',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Special flags: ABS (absent), INC (incomplete), CHEAT (cheating)',
               existing_nullable=True)
    op.alter_column('absence_excusals', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, approved, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table('projects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('contractor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'planned'::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress_percent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('projects_created_by_fkey')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('projects_school_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_school_id'), 'projects', ['school_id'], unique=False)
    op.drop_index(op.f('ix_consent_records_student_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_bed_allocations_student_id'), table_name='bed_allocations')
    op.drop_index(op.f('ix_bed_allocations_room_id'), table_name='bed_allocations')
    op.drop_index(op.f('ix_bed_allocations_academic_year_id'), table_name='bed_allocations')
    op.drop_table('bed_allocations')
    op.drop_index(op.f('ix_alumni_profiles_student_id'), table_name='alumni_profiles')
    op.drop_index(op.f('ix_alumni_profiles_school_id'), table_name='alumni_profiles')
    op.drop_table('alumni_profiles')
    op.drop_index(op.f('ix_rooms_hostel_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_events_school_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_data_subject_requests_requester_id'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_hostels_school_id'), table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_building_projects_status'), table_name='building_projects')
    op.drop_index(op.f('ix_building_projects_school_id'), table_name='building_projects')
    op.drop_table('building_projects')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assignments_subject_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_class_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
