import re

file_path = 'apps/backend/alembic/versions/41745a2b1bf7_add_modules.py'
with open(file_path, 'r') as f:
    content = f.read()

# Find all drop_constraint that are AFTER alter_column and move them BEFORE alter_column
pattern = r"(    op\.alter_column\('([^']+)', '([^']+)',\n(?:               .*?\n)*?)(    op\.drop_constraint\(op\.f\('([^']+)'\), '[^']+', type_='foreignkey'\)\n)"

# This regex is a bit tricky to get right, let's just do a simpler script to find and move drop_constraint
# Actually, the error says:
# "foreign key constraint "discipline_records_reported_by_fkey" cannot be implemented"
# wait, the error happened during UPGRADE!
# "Running upgrade 014_governance_schema -> 41745a2b1bf7"
# So it's trying to alter the column while the foreign key still exists.
# We need to drop the foreign key BEFORE altering the column.
# Let's just find all drop_constraint for foreign keys and move them to the top of the upgrade() function.

import re

# Find all drop_constraints in upgrade()
upgrade_start = content.find('def upgrade()')
downgrade_start = content.find('def downgrade()')

upgrade_content = content[upgrade_start:downgrade_start]

drop_constraints = re.findall(r"    op\.drop_constraint\(.*?\n", upgrade_content)
for dc in drop_constraints:
    upgrade_content = upgrade_content.replace(dc, '')

# Add them right after def upgrade():\n    # ### commands auto generated by Alembic - please adjust! ###\n
insertion_point = upgrade_content.find('###\n') + 4
new_upgrade_content = upgrade_content[:insertion_point] + "".join(drop_constraints) + upgrade_content[insertion_point:]

content = content[:upgrade_start] + new_upgrade_content + content[downgrade_start:]

with open(file_path, 'w') as f:
    f.write(content)
print("Moved drop_constraints to top of upgrade()")
