import os
import secrets
import string


def _generate_password(length: int = 24) -> str:
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def generate_env_local(ports: dict, project_root: str):
    """Generate a .env.local file with dynamically allocated ports."""
    env_local_path = os.path.join(project_root, '.env.local')

    postgres_password = _generate_password()
    couchdb_password = _generate_password()
    couchdb_secret = _generate_password(32)
    jwt_secret = _generate_password(48)
    app_secret = _generate_password(48)

    # Base configuration mapping
    config = {
        'FRONTEND_PORT': ports['frontend'],
        'BACKEND_PORT': ports['backend'],
        'POSTGRES_PORT': ports['postgres'],
        'POSTGRES_USER': 'edulafia',
        'POSTGRES_PASSWORD': postgres_password,
        'POSTGRES_DB': 'edulafia',
        'REDIS_PORT': ports['redis'],
        'COUCHDB_PORT': ports['couchdb'],
        'COUCHDB_USER': 'admin',
        'COUCHDB_PASSWORD': couchdb_password,
        'COUCHDB_SECRET': couchdb_secret,
        'JWT_SECRET_KEY': jwt_secret,
        'APP_SECRET_KEY': app_secret,
        'VITE_API_URL': f"http://localhost:{ports['backend']}",
        'DATABASE_URL': f"postgresql+asyncpg://edulafia:{postgres_password}@localhost:{ports['postgres']}/edulafia",
        'REDIS_URL': f"redis://localhost:{ports['redis']}/0",
    }

    with open(env_local_path, 'w') as f:
        f.write("# AUTO-GENERATED BY start-dev.py\n")
        f.write("# DO NOT EDIT MANUALLY\n\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")

    return config
