from fpdf import FPDF
import tempfile
import os

def generate_report_card_pdf(student_name: str, term_name: str, school_name: str, scores: list) -> str:
    """Generate a simple PDF report card and return the temporary file path."""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, school_name, align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Student Report Card", align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 10, f"Name: {student_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Term: {term_name}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Table Header
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(80, 10, "Subject", border=1)
    pdf.cell(30, 10, "CA Score", border=1)
    pdf.cell(30, 10, "Exam Score", border=1)
    pdf.cell(30, 10, "Total", border=1, new_x="LMARGIN", new_y="NEXT")
    
    # Table Body
    pdf.set_font("helvetica", "", 12)
    for score in scores:
        pdf.cell(80, 10, str(score.get("subject", "N/A")), border=1)
        pdf.cell(30, 10, str(score.get("ca", "0")), border=1)
        pdf.cell(30, 10, str(score.get("exam", "0")), border=1)
        pdf.cell(30, 10, str(score.get("total", "0")), border=1, new_x="LMARGIN", new_y="NEXT")
        
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by Edulafia Platform", align="C")
    
    # Save to temp file
    fd, temp_path = tempfile.mkstemp(suffix=".pdf", prefix="report_card_")
    os.close(fd)
    
    pdf.output(temp_path)
    return temp_path